Updated wrapper

diff --git a/wrapper b/wrapper
--- a/wrapper
+++ b/wrapper
@@ -26,18 +26,16 @@ else
   BINARY_NAME=$(basename "$0")
 fi
 
-MAIN=""
-
-if [ -z "$MAIN" ]; then
-  MAIN="$(find "$APPDIR/bin" "$APPDIR/usr/bin" -iname "$BINARY_NAME" -print -quit)"
-fi
-
-if [ -z "$MAIN" ]; then
-  MAIN="$(find "$APPDIR/bin" "$APPDIR/usr/bin" -iname "$1" -print -quit)"
-fi
-
-if [ -z "$MAIN" ]; then
-  MAIN="$(find "$APPDIR/bin" "$APPDIR/usr/bin" \( -iname "wine" -o -iname "wine64" \) -print -quit)"
+if   read -r MAIN < <(find "$APPDIR/bin" "$APPDIR/usr/bin" -iname "$BINARY_NAME" -print -quit); then
+  echo "INFO:wine: '$MAIN $*'"
+elif read -r MAIN < <(find "$APPDIR/bin" "$APPDIR/usr/bin" -iname "$(basename "$1")" -print -quit); then
+  shift
+  echo "INFO:wine: '$MAIN $*'"
+elif read -r MAIN < <(find "$APPDIR/bin" "$APPDIR/usr/bin" \( -iname "wine" -o -iname "wine64" \) -print -quit); then
+  echo "INFO:wine: '$MAIN $*'"
+else
+  echo "ERR:wine binaries not found"
+  exit 1
 fi
 
 "$MAIN" "$@"
